### ISSUE TITLE
Update Zizia to run against (Hyrax) supported versions of Ruby & Rails

### ISSUE THREAD

**Issue by maxkadel** [curationexperts/zizia#93]
Zizia runs against Hyrax supported versions of Ruby and Rails in CI

**Comment by fnibbit** [comment]
Moving from Ruby 2.6.5 to Ruby 2.7.1 turns this deprecation into an error: /Users/rkadel/.rvm/gems/ruby-2.6.5@zizia/gems/activesupport-5.1.7/lib/active_support/number_helper/rounding_helper.rb:37: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.

Specifying hyrax 2.5 prevented using rails 5.2, experimenting with loosening hyrax dependency  to 2.
