### ISSUE TITLE
Mint a new release of Zizia and publish to Rubygems

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/zizia#95]

**Comment by fnibbit** [comment]
Max+I tagged a release; the push to rubygems timed out a couple of times and then gave the error copied below, so we're going to try it another time:

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    
    <title>Unicorn! | RubyGems.org</title>
  </head>
  <body style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif">
    <div style="margin-right: auto; margin-left: auto; width: 90%; max-width: 940px;">
      <div style="padding-top: 60px; position: relative;">
        <object height="530" type="image/svg+xml" alt="503 error" style="width: 100%;" data="/images/sea_level.svg"></object>
      </div>
      <div style="margin-right: auto; margin-bottom: 120px; margin-left: auto; max-width: 680px; text-align: center;">
        <h1 style="margin-top: 25px; margin-bottom: 8px; font-weight: 200; font-size: 60px; ">Unicorn!</h1>
        <p style="font-weight: 300; font-size: 18px; line-height: 1.66; ">We are having a bad problem and the app server will not talk to us.</p>
        <a href="/" style="font-weight: 300; font-size: 18px; line-height: 1.66;  text-decoration: none; color: #e9573f;">Back to RubyGems.org</a>
      </div>
    </div>
  </body>
</html>

**Comment by fnibbit** [comment]
Went back to retry the push today and the version we were pushing Friday (6.0.1) shows up as having been pushed Friday.
